# Generated by Django 6.0.2 on 2026-03-04 09:10

from django.db import migrations


def update_user_roles(apps, schema_editor):
    """Update all STAFF roles to MEMBER"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='STAFF').update(role='MEMBER')


def reverse_update_user_roles(apps, schema_editor):
    """Reverse: update MEMBER roles back to STAFF (if needed)"""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='MEMBER').update(role='STAFF')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(update_user_roles, reverse_update_user_roles),
    ]
