# Generated by Django 6.0.2 on 2026-03-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_staff_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('CLIENT', 'Client')], default='CLIENT', help_text="User's role determines system access and permissions", max_length=10),
        ),
    ]
