# Generated by Django 6.0.2 on 2026-03-04 09:04

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


def migrate_staff_to_member(apps, schema_editor):
    """Migrate existing Staff data to Member"""
    Member = apps.get_model('tickets', 'Member')
    Staff = apps.get_model('tickets', 'Staff')
    
    for staff in Staff.objects.all():
        Member.objects.create(
            id=staff.id,
            user=staff.user,
            specialty=staff.specialty,
            is_active=staff.is_active,
            created_at=staff.created_at,
            updated_at=staff.updated_at,
        )


def reverse_migrate_staff_to_member(apps, schema_editor):
    """Reverse the migration"""
    Member = apps.get_model('tickets', 'Member')
    Member.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subissue_unique_together_alter_subissue_issue'),
        ('tickets', '0005_ticketactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.issue')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_staff_to_member, reverse_migrate_staff_to_member),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='issue', chained_model_field='specialty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.member'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
