# Generated by Django 6.0.2 on 2026-03-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_member_alter_ticket_assigned_to_delete_staff'),
    ]

    operations = [
    ]
