# Generated by Django 6.0.2 on 2026-03-04 10:44

from django.db import migrations


def cleanup_orphaned_assigned_to(apps, schema_editor):
    """Set assigned_to to NULL for tickets with orphaned member references"""
    Ticket = apps.get_model('tickets', 'Ticket')
    Member = apps.get_model('tickets', 'Member')
    
    # Get all existing member IDs
    valid_member_ids = set(Member.objects.values_list('id', flat=True))
    
    # Find tickets with invalid assigned_to_id
    tickets_to_fix = Ticket.objects.exclude(assigned_to__isnull=True)
    fixed_count = 0
    
    for ticket in tickets_to_fix:
        if ticket.assigned_to_id and ticket.assigned_to_id not in valid_member_ids:
            ticket.assigned_to_id = None
            ticket.save(update_fields=['assigned_to_id'])
            fixed_count += 1
            print(f"Fixed Ticket {ticket.id}: cleared orphaned assigned_to_id")
    
    print(f"Cleanup complete: {fixed_count} tickets fixed")


def reverse_cleanup(apps, schema_editor):
    """Nothing to reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_staff_to_member'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_assigned_to, reverse_cleanup),
    ]
