# Generated by Django 6.0.2 on 2026-03-05 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subissue_unique_together_alter_subissue_issue'),
        ('tickets', '0008_cleanup_orphaned_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(help_text='Name of the client company/organization', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_type',
            field=models.ForeignKey(help_text='Classification of company type (e.g., IT, Healthcare)', on_delete=django.db.models.deletion.PROTECT, to='core.companytype'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_duration',
            field=models.CharField(blank=True, help_text='Duration/terms of the contract with client', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Primary email address for client communication', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(help_text='Associated user account with CLIENT role', limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='whatsapp_number',
            field=models.CharField(help_text='WhatsApp number for direct client communication', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If False, member will not be assigned new tickets'),
        ),
        migrations.AlterField(
            model_name='member',
            name='specialty',
            field=models.ForeignKey(help_text='The issue type/category this member specializes in', on_delete=django.db.models.deletion.PROTECT, to='core.issue'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(help_text='Associated user account with MEMBER role', limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
